// Generated by CoffeeScript 1.7.1
var MainRouter,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

MainRouter = (function(_super) {
  __extends(MainRouter, _super);

  function MainRouter() {
    this.home = __bind(this.home, this);
    return MainRouter.__super__.constructor.apply(this, arguments);
  }

  MainRouter.prototype.routes = {
    '': 'home'
  };

  MainRouter.prototype.home = function() {
    return this.navigate('someRoute', {
      trigger: true,
      replace: true
    });
  };

  return MainRouter;

})(Marionette.AppRouter);

module.exports = MainRouter;
